import turtle

turtle.Screen().bgcolor("lightblue")
turtle.shape("turtle")
sc=turtle.Screen()
turtle.color("blue")
sc.setup(width=600, height=600)
turtle.title("Turtle Drawing")
t=turtle.Turtle()
t.speed(1)
t.forward(100)
t.left(120)  
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.penup()
t.goto(-50, -50)
t.pendown()
t.color("red")
t.circle(50)
t.penup()
t.goto(100, 100)
t.forward(50)
t.right(90)
t.pendown()
t.color("blue")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.color("blue")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.color("blue")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.color("green")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.color("green")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.color("green")
t.forward(100)
t.forward(50)
t.right(90)
t.pendown()
t.forward(150)

turtle.done()